---
title: "Practice 1"
author: "Michael Friedman"
date: "6/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```


```{r}
x <- seq(1, 10, 1)
y <- seq(1, 50, 5)

df <- as.data.frame(cbind(x, y))

plot(df$x, df$y)
```

#add my own data to rmd file
```{r}
sample <- read.csv("growth measurements.csv")

sample_lm <- lm(Bud_growth ~ Species*Light, data = sample)
sample_anova <- anova(sample_lm)
sample_lm_output <- summary(sample_lm)

sample_anova
sample_lm_output
```

#add more data to rmd file
```{r}
test <- read.csv("test_data.csv")
test_lm<- lm(Count ~ Year*Site, data = test) 
test_anova<- anova(test_lm)
test_lm_output<- summary(test_lm)

test_anova
test_lm_output

#make a plot of data
ggplot(data = test, aes(x = Site, y = Count, color = Year)) +
  geom_point(aes(x = Site, y = Count, color = Year), position = 'jitter') +
  geom_boxplot(aes(x = Site, y = Count), alpha = 0.5)

#save plot
ggsave("Molly_testdata.jpeg", plot = last_plot(), device = jpeg())
```

```{r}
#input results as notes

test_anova
#Analysis of Variance Table

#Response: Count
#          Df Sum Sq Mean Sq F value  Pr(>F)  
#Year       1   1.07   1.066  0.1402 0.70915  
#Site       1  21.00  21.002  2.7617 0.10089  
#Year:Site  1  33.36  33.361  4.3868 0.03974 *
#Residuals 72 547.56   7.605                  
#---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

test_lm_output

#Call:
#lm(formula = Count ~ Year * Site, data = test)

#Residuals:
#    Min      1Q  Median      3Q     Max 
#-4.7020 -2.2066 -0.1157  2.2011  5.6323 

#Coefficients:
#             Estimate Std. Error t value Pr(>|t|)   
#(Intercept)   3.39516    0.99831   3.401   0.0011 **
#Year          0.13893    0.05280   2.631   0.0104 * 
#Sitetrx       1.46566    2.08643   0.702   0.4847   
#Year:Sitetrx -0.13012    0.06213  -2.094   0.0397 * 
#---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#Residual standard error: 2.758 on 72 degrees of freedom
#Multiple R-squared:  0.09193,	Adjusted R-squared:  0.05409 
#F-statistic:  2.43 on 3 and 72 DF,  p-value: 0.0722
```



